yuda wardana
fearless-fox-2019/mini-wp pull request #24
Opened 2019-07-22 01:58 UTC by Yudawardana94

environtment yang digunakan: 

DB_SERVER=mongodb://localhost:27017/adioos
PORT=3000
JWT_SECRET=hallohallobandung
GOOGLE_CLIENT_ID=132166001773-8hdrtj1nhu45na8h87365uoilltf66ks.apps.googleusercontent.com
CLOUD_BUCKET=foxshares
GCLOUD_PROJECT=yudawardana-1560407905203
KEYFILE_PATH=keyfile.json
NEWS_API_KEY=d39e3d69c0ae4196838de9765659704d

2019-07-22 04:23 UTC, Yudawardana94 commented
https://documenter.getpostman.com/view/8079965/SVSNKo7a?version=latest

lupa mas ini dokumentasinya..

untuk kesulitannya :
1. saya kemaren masih bingung buat ngebaca tag HTMLnya buat nampilin contentnya waktu di timeline. sebabnya contetnya saya potong biar text kurang dari 220 character. waktu di v-html dia ngga bisa karena motongnya pake pakcakge sendiri.
2.

2019-07-23 09:06 UTC, dmtrxw reviewed
# App
- Untuk input yang harus disubmit pake enter, kasih button aja
- Kalo mau search yang sambil ketik, nama metodenya `debounce search`
- Loading hanya ditampilkan ketika input benar/berhasil
- Mestinya gabisa follow diri sendiri
- Ketika update dan ganti gambar, gambar lama harus dihapus dari GCS
- Jodit: https://www.npmjs.com/package/jodit-vue

# Code
Code review nanti gw update @Yudawardana94

2019-07-26 04:38 UTC, dmtrxw requested changes

2019-07-26 04:38 UTC, dmtrxw commented on server/app.js
> +    mongoose.connect(`${process.env.DB_SERVER}`, {
Ga DRY, sama dengan line 22 cuma beda parameter pertama. Refactor ya

2019-07-26 04:38 UTC, dmtrxw commented on server/controllers/articleController.js
> +            image: cloudStoragePublicUrl || 'https://images.unsplash.com/photo-1560787139-1394d216a73e?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=720&ixlib=rb-1.2.1&q=80&w=1080',
File untuk default image harus di-save ya. Kalo misalkan sourcenya udah gaada di internet lu jadi harus cari gambar lain 😅

2019-07-26 04:38 UTC, dmtrxw commented on client/src/App.vue
> +import searchbytag from "./components/searchbytag.vue";
Nama file harus konsisten, kalo camelCase ya camelCase semua

2019-07-26 04:38 UTC, closed without merging